/* Downloads the web fonts from Google Fonts into assets/fonts/ and writes
   css/fonts.css pointing at the local copies.

   Run once, or again to pick up a font update; the output is committed. The
   site must not load fonts from Google at runtime: it costs a third-party
   connection on every visit, and in the EU serving Google Fonts hands a
   visitor's IP to Google without consent.

   Variable fonts are used, so one file per subset covers every weight. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = path.join(ROOT, "assets", "fonts");

// The site is English and Greek; the other subsets Google serves are dead weight.
const SUBSETS = ["latin", "latin-ext", "greek", "greek-ext"];

const SRC =
  "https://fonts.googleapis.com/css2" +
  "?family=Inter:wght@400..700" +
  "&family=Manrope:wght@600..800" +
  "&display=swap";

// Without a browser UA, Google serves the legacy ttf stylesheet.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const css = await (await fetch(SRC, { headers: { "User-Agent": UA } })).text();

fs.mkdirSync(FONT_DIR, { recursive: true });

const out = [
  "/* Self-hosted web fonts. Generated by tools/fetch-fonts.mjs — do not edit.",
  "   Variable fonts: one file per subset covers the whole weight range. */",
  "",
];

// Each @font-face in the response is preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
let kept = 0;

for (const [, subset, block] of blocks) {
  if (!SUBSETS.includes(subset)) continue;

  const family = block.match(/font-family: '([^']+)'/)[1];
  const url = block.match(/url\((https:\/\/[^)]+)\)/)[1];
  const file = `${family.toLowerCase()}-${subset}.woff2`;

  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  fs.writeFileSync(path.join(FONT_DIR, file), bytes);

  out.push(
    `/* ${family} · ${subset} */`,
    block
      .replace(/url\(https:\/\/[^)]+\)/, `url(../assets/fonts/${file})`)
      .replace(/^\s*/gm, (m) => m.replace(/\n/g, "")),
    ""
  );

  console.log(`  ${file.padEnd(28)} ${(bytes.length / 1024).toFixed(1)} KB`);
  kept++;
}

if (!kept) {
  console.error("No matching @font-face blocks — the upstream CSS format changed.");
  process.exit(1);
}

fs.writeFileSync(path.join(ROOT, "css", "fonts.css"), out.join("\n"));
console.log(`\n${kept} files -> assets/fonts/, css/fonts.css written.`);
